### ISSUE TITLE
닉네임저장 API

### ISSUE THREAD

**Issue by foxsea** [chanoo/klock-api#13]

**Comment by chanoo** [comment]
닉네임 저장도 

회원정보 가입/수정으로 통으로 하는건 어떤가요??
회원 가입 프로세스 마지막 단계에 다 밀어 넣는게 좋겠습니다~

**Comment by foxsea** [comment]
기존에 회원정보 수정 api가 있는데 
`PUT("/{id}", userHandler::updateUser`
body에 아래 정보 같이 보내주는걸로 되어 있어

```
data class UpdateUserRequest(
  val nickname: String,
  val tagId: Long,
  val startOfTheWeek: DayOfWeek,
  val startOfTheDay: Int,
  val updatedAt: LocalDateTime = LocalDateTime.now()
)
```
여기에 닉네임포함되어 있는데
이거와 별도로 닉네임만 수정하는 게 필요한가?
@chanoo

**Comment by foxsea** [comment]
리마인드 @chanoo

**Comment by chanoo** [comment]
설명 주신걸로 해결 함
