### ISSUE TITLE
회원 가입 API

### ISSUE THREAD

**Issue by chanoo** [chanoo/klock-api#15]
1. 닉네임
2. 한주의 시작
3. 하루의 시작
4. 태그
5. 프로필 이미지

1,2,3,4 를 회원 가입 API
5 프로필 등록 API

**Comment by chanoo** [comment]
위와 같이 하는건 어떤가요?

**Comment by foxsea** [comment]
1,2,3,4를 한번에 저장하는게 아닌거지?
로그인후에 한 화면씩 하는거라 중간에 멈출수도 있고 하니 각각 저장을 하는게 좋을것 같은데.

**Comment by foxsea** [comment]
어 그래~ 
그럼 /api/signup api 에서 처리하는걸로 하고 나중에 UX나 사용자 피드백을 받아보고 개선하는 걸로!
