### ISSUE TITLE
닉네임 체크 API

### ISSUE THREAD

**Issue by foxsea** [chanoo/klock-api#18]

**Comment by foxsea** [comment]
닉네임 최대 길이 및 허용 문자 정의 필요
@chanoo

**Comment by foxsea** [comment]
컬럼명 수정해야 할 것 같은데?
userName - > nickName

**Comment by chanoo** [comment]
네네 변경합시다요!

**Comment by foxsea** [comment]
[ migration script ]
alter table klk_user change username nickname varchar(255) not null
