### ISSUE TITLE
친구 QR코드 생성 API

### ISSUE THREAD

**Issue by foxsea** [chanoo/klock-api#22]

**Comment by foxsea** [comment]
QR코드찍으면 클라크 앱 실행시켜서 QR코드로 친구 팔로우하는 화면까지 가야 하니
앱 scheme을 포함시켜서 QR코드 생성해야 될 것 같아.
그러면 서버에서는 어디까지 해서 넘겨주면 될지 정해야 할 필요가 있을 듯.
@chanoo

**Comment by chanoo** [comment]
QR 코드로 스캔하면 맞팔이 되어야 하니
JSON 형태로 대칭키 암호화 해서 주고 받으면 좋을거 같습니다.
json 에는 아래 요소가 있으면 될것 같은데

발급시간, 유효시간(발급시간으로부터 10분), 내 user id, 상대방 user id 

위 json 을 대칭키로 암호화 하구요~

**Comment by chanoo** [comment]
scheme는 제가 다시 정의 해서 알려드릴께여~

**Comment by chanoo** [comment]
api 에서 코드만 생성 하면 되네여
코드를 가져와서 제가 qr 코드 이미지 생성 할께여~
qr코드 이미지를 서버에서 생성 해야 할까요?

@foxsea

**Comment by foxsea** [comment]
qr코드가 어차피 맞팔하기 위한 중간 매개체인거라
실제 맞팔 api를 만들 예정이고 위에서 정의했듯이 거기에 포함될 json 정보가 
발급시간, 유효시간(발급시간으로부터 10분), 내 user id, 상대방 user id이니 
이중에 qr코드에는 상대방 user id 정보만 있으면 될것 같아.

결국은 qr코드에 나의 user id 정보만 들어 있으면 되는건데 이건 클라가 알고 있는 정보임.

따라서 아래 2가지 요소 체크해서 결정해야 할듯.
1. 클라에서 api 없이 qr 생성 가능하니 그냥 클라가 처리할건지? 
2. qr code에 user id가 노출될수는 있으니 보안상 이슈 발생할지 검토

**Comment by foxsea** [comment]
qr code 이미지를 서버에서 생성하면 스키마 변경시 기존 qr code 모두 폐기해야 하는 이슈가 발생할 수 있을 듯.

**Comment by chanoo** [comment]
클라에서 qr 코드를 생성하고
클라에서 qr 스캔 하면 api에 json 던져 주면
복호화 해서 유효 시간 체크 해서 친구 추가 하는걸로 하면 될듯요~
hmac 으로 무결성 검증 하고요~

https://chat.openai.com/share/79d340f4-864c-4dd0-b1d5-a65bf634e084

**Comment by foxsea** [comment]
클라에서 json암호화해서 준다는거지?
key는 어떻게 공유할까?

**Comment by chanoo** [comment]
1. 네 암호화 해서 보내드릴께여~
2. 16바이트 aes 암호키 생성해서 공유 할께여~!

아니면
1. rsa 방식이 제일 안전하긴 한데...
2. rsa 로 하면 암호화할 수 있는 텍스트 길이가 제한 되어 있어서 좀 복잡하게 되여~
3. 공개키, 개인키 jks 파일을 생성해서 유저 로그인 할때 공개키를 같이 내려 줍니다.
4. 클라에서 랜덤한 aes 키를 16바이트 키를 생성하고
5. aes 키를 rsa 로 공개키로 암호화 해서 json 에 실어서 보내면
6. 서버에서 개인키로 json 의 aes 키를 풀어서
7. json 에 실어서 온 암호문을 복호화한 aes 키로 풀면 되긴 합니다

고민 해주세요~

**Comment by foxsea** [comment]
rsa 방식으로 한번 해볼께~

**Comment by chanoo** [comment]
[klock.jks.zip](https://github.com/chanoo/klock-api/files/13749540/klock.jks.zip)

jks 파일입니다.

alias 는 klock 입니다.
저장소 비번은 Klock1324!
klock alias 비번은 Klock1324! 
입니다.

공개키를 UserInfo 에 같이 실어서 내려주시면 될듯 해여~

**Comment by foxsea** [comment]
alias, 비번은 aws키 와 동일하게 처리할까?

**Comment by chanoo** [comment]
새로 jks 파일 만드셨으면
나중에 변경 될수 있으니깐
다르게 해서 주세여~

**Comment by foxsea** [comment]
새로 만든건 아니고 니가 만들어준거 쓸건데
alias 랑 비번을 소스코드에 박아두긴 그래서 
aws access/secret key 처럼 처리하는게 좋지 않을까 해서.

**Comment by chanoo** [comment]
아 네네~

**Comment by foxsea** [comment]
export KEY_STORE_PASSWORD=${{ secrets.KEY_STORE_PASSWORD }}
export KEY_ALIAS=${{ secrets.KEY_ALIAS }}
secrets에 추가해줘

**Comment by chanoo** [comment]
등록 했습니다~!

**Comment by foxsea** [comment]
친구 QR코드 생성은 클라에서 하는 것으로 결정되어 해당 이슈는 종료 처리!
