### ISSUE TITLE
담벼락 리스트 API

### ISSUE THREAD

**Issue by foxsea** [chanoo/klock-api#24]
![Image](https://github.com/chanoo/klock-api/assets/3335290/91f409e6-cf9e-4432-9e0a-5edeee1df62f)

**Comment by foxsea** [comment]
케릭터(?) 아이콘은 사용자 프로필 이미지인건가? @chanoo

**Comment by chanoo** [comment]
네네 사용자 프로필 이미지입니다
디폴트로 캐릭터 이미지를 넣을 예정입니다요
