### ISSUE TITLE
친구 목록 API

### ISSUE THREAD

**Issue by chanoo** [chanoo/klock-api#38]
친구 목록 API 개발
  - 닉네임
  - 프로필 이미지
  - 총공부 시간 (일간, 주간, 월간 데이터를 뽑을수 있도록 고려 필요)
  - 공부 제일 많이 한 친구 1명만 제일 위에 
  - 나머지는 가나다 순서

![Image](https://github.com/chanoo/klock-api/assets/3335290/e84e5341-b3fb-4506-9d26-e64d7ecdf80b)

**Comment by foxsea** [comment]
프로필 이미지는 아직 없음 
프로필 이미지 등록 API 추가 필요

**Comment by chanoo** [comment]
회원 가입 하는 과정에 프로필 이미지 등록 만들께요
설정에서 프로필 이미지 등록 하는 기능도 추가 하겠습니다!
