### ISSUE TITLE
담벼락 공부 시작, 종료시 쓰레드 등록 API

### ISSUE THREAD

**Issue by chanoo** [chanoo/klock-api#39]

**Comment by foxsea** [comment]
{name} 공부를 시작했어요.
{name} 공부를 종료했어요.

**Comment by chanoo** [comment]
api 에 속성으로 이름이 표시 되면 될듯 합니다~

**Comment by foxsea** [comment]
아 그러고보니 api 구나.
공부 세션 생성시 시작 담벼락 생성하고
공부 세션 업데이트시 종료 담벼락 생성하게 해놓았는데
api로 하는게 좀 더 유연하게 쓸 수 있겠지?
@chanoo

**Comment by chanoo** [comment]
담벼락에 시스템 메시지로 남길지 내가 남길지도 있으면 좋을듯 하네요

**Comment by chanoo** [comment]
공부 세션 시작 종료시 남기면 될듯 해여~
시스템이 남기는 메시지가 생길듯 한데요

**Comment by foxsea** [comment]
시스템 메시지는 세션 시작 종료시 남기는걸로.
한가지 확인) 세션 업데이트가 종료가 맞는거지? 

시스템 메시지 or 내가 남길건지에 대한 부분은 세부 논의가 필요할듯.
일단 현재는 시스템 메시지로만 처리

**Comment by foxsea** [comment]
마무리하게 위 내용 확인해줘.  @chanoo

**Comment by chanoo** [comment]
내용 확인 하던 중에

지금은 공부 시작하고 종료가 되면 서버에 보내서 공부 시간을 기록 하도록 되어 있어요

공부를 하다가 앱을 강제로 종료 한경우
종료할 때 담벼락에 남지 않아요..

1. 기존 로직대로 하고, 내가 남기도록 한다
2. 시스템에서 남기도록 하고 공부 시작할때도 서버에 기록 한다.

1번대로 하면 내가 공부를 시작하고 10초 내에 취소 할 경우 기록이 되지 않도록 해야 하는데...
공부 시작 하다 만것도 남기는게 맞는건지...

일단 1번대로 가야 하는건 맞는거 같은데..
어찌 생각하셔요?

**Comment by foxsea** [comment]
공부 시작하고 10초이내 취소하는 이슈가 있으니..
이때는 공부 시작 기록을 하면 안될것 같아.
공부 종료시에만 세션 api 통해서 담벼락 남기는 것은 일관성이 없는것 같아 보이네.

그래서 서버에서 세션시 담벼락 자동 기록 처리하는 부분은 안하는게 나을 것 같고
담벼락 기록 api를 통해 클라이언트에서 꼭 시작/종료가 아니더라고 특정 이벤트에 남길 수 있도록 하면 좋을 것 같아 보이네.

**Comment by chanoo** [comment]
네네 저도 계속 고민 해봐도
그렇게 하는게 최선일듯 하네요!

**Comment by foxsea** [comment]
해당 api는 기존 api로 대체가능하여 필요없어져서 종료 처리
