### ISSUE TITLE
공부 세션의 timer_name 변경 api

### ISSUE THREAD

**Issue by foxsea** [chanoo/klock-api#50]
제가 사용하다가

타이머를 실행하고
국어 공부 타이머를 실행하고
실제로 수학 공부를 했으면
수정할 방법이 없더라구요

피료~

**Comment by foxsea** [comment]
공부 세션 키는 클라가 알고 있는거지?
@chanoo

**Comment by chanoo** [comment]
let id: Int64?
    let userId: Int64
    let startTime: Date
    let endTime: Date
    let timerName: String
    let timerType: String

요렇게 알고 있습니다~
