### ISSUE TITLE
QR코드 발급정보 수정

### ISSUE THREAD

**Issue by chanoo** [chanoo/klock-api#54]
Qr코드에
발급일, 종료일, 팔로우 아이디, 사용자아이디
이렇게 보내는데

누가 qr코드를 찍을지 모르기 때문에
스캔하는 사용자의 아이디를 jwt 토큰으로 파악해서 추가 해야 하네요

먼가 찜찜 했는데
만들다 보니 보이네요

**Comment by foxsea** [comment]
그럼 서버에서 json 데이터에 있는 사용자 아이디가 jwt토큰에 있는 스캔 사용자 아이디와 같은지 체크하면 되는거 아닌가?

**Comment by chanoo** [comment]
Json에는 누가 찍을지 정보가 없어요

스캔 하는 사람이 암호화 된 qr코드데이터를 api로 보낼거니
Api에 같이 실어서 보내는 jwt데이터를 읽어서 맞팔해줄 상대가 되는거에요

userid가 빠져요
