### ISSUE TITLE
시험시간 타이머에 markingTime 추가

### ISSUE THREAD

**Issue by chanoo** [chanoo/klock-api#6]
답안지 마킹 시간을 입력 할수 있도록 컬럼 추가

**Comment by chanoo** [comment]
컬럼 Pomodoro 타이머의 경우 restTime을 breakTime으로 변경 요청 드려요
breakTime에 더 맞는거 같아여~

@foxsea

**Comment by foxsea** [comment]
- 시험 시간 타이머에 markingTime 추가 완료 

> - Table에도 반영

- 뽀모도로 타이머 restTime -> breakTime 변경 

> - 에러날 수 있어서 Table에는 변경하지 않았음

**Comment by chanoo** [comment]
배포 부탁 드려요~
테이블도 같이 변경 해주세요

**Comment by foxsea** [comment]
배포 완료!
