### ISSUE TITLE
UserTraceHeart 추가, 삭제 API 개발

### ISSUE THREAD

**Issue by chanoo** [chanoo/klock-api#60]
UserTrace에 heart 가 이상해요 boolean 값이에요

UserTraceHeart 테이블에
속성으로 좋아요한 사람의 userid, count 정보가 들어가야 되요
한사람이 여러번 눌러서 좋아요 감정을 많이 들어가는게 뽀인트

UserTrace에 heart_count가 있어서
usertraceheart 의 count 총합이 들어가면 됨

**Comment by chanoo** [comment]
@foxsea 요거 개발 부탁드립니다~

**Comment by foxsea** [comment]
@chanoo 삭제가 필요한 이유는? 하트 취소할수도 있는건가?

**Comment by chanoo** [comment]
다른 서비스들도 좋아요가
한번 누르면 좋아요가 되고
한번 더 누르면 좋아요가 취소 됩니다

우리는 여러번 누르면 좋아요 감정을 크게크게 표현 할 수 있도록 했습니다.
좋아요 취소는 꾹 눌러서 취소 할수도 있고요
