### ISSUE TITLE
타이머별 공부시간 세션 구분해서 등록

### ISSUE THREAD

**Issue by chanoo** [chanoo/klock-api#7]
공부시간 세션을 구분해서 저장할수 있게 개발
 - 어떤 공부를 했는지만 알면 될듯
 - 타이머를 지워도 공부시간은 남아 합니다.
 - 공부 시간 세션에 타이머 이름을 기록 하면 될것 같습니다.
 - 의견주셔요

**Comment by foxsea** [comment]
TimerType 하고 해당 Timer ID를 추가하면 되겠네.
그리고 타이머 삭제시 실제 데이터를 지우는게 아니라 flag(on/off)로 처리하는게 좋지 않을까?
그리고 subject id는 필요없을듯한데?

**Comment by chanoo** [comment]
국어공부 집중 시간 타이머를 등록 하고 

1. 국어 공부 포커스 타이머를 등록하고 공부 시작
2. 국어 공부 포커스 타이머를 삭제
3. 같은 이름의 국어 공부 타이머를 등록해서 공부 시작

나중에 통계를 잡을때 하나의 통계로 봐야 할것 같아요
집중시간 타이머로 국어 공부 할수 있고 뽀모도로로 국어 공부를 할수 있거든요.

**Comment by foxsea** [comment]
그렇다면 국어 공부라는 키가 같아야 하는데 
1. "국어 공부" 주제를 등록
2. 포커스 타이머 등록시 "국어 공부" 주제 선택
3. 공부시작종료 세션기록 (기록시 타이머 타입등록)
4. 포커스 타이머 삭제
5. 뽀모도로 타이버 등록시 "국어 공부" 주제 선택
...

이런식이면 연결이 될듯

**Comment by foxsea** [comment]
그러면 주제 기준으로 히스토리 , 통계도 볼 수 있네

**Comment by chanoo** [comment]
주제는 타이머 제목으로 주제가 자동 등록 되는걸까요?

열품타 보니깐 같은 이름으로 여러개의 타이머를 등록하고 삭제 해도
타이머 이름 별로 통계가 1개로 잡히네여.

**Comment by foxsea** [comment]
주제는 타이머랑 별개로 최초에 등록해야겠지?
그러니까 나 이런이런 공부/시험을 할거를 정한후에 그걸 하기 위해서 돕는 수단이 타이머인거잖아.
그런 의미라면 주제로 들어가서 타이머 생성하면 해당 주제에 타이머가 붙는 형태가 되는거지 않을까.

**Comment by chanoo** [comment]
타이머를 사용하기 위해 주제를 등록 하면 허들이 높은거 같아요
주제가 없어도 공부 세션에 제목으로만 통계를 뽑아내도 될것 같아요.

**Comment by foxsea** [comment]
보통 타이머를 잘 삭제하지 않는다면 말한 방식대로 해도 무방할것 같고..

**Comment by chanoo** [comment]
좋은 생각이심!!
지금은 시간이 관계상 제목만으로 좋을것 같고

타이머 이름을 입력할 때
1. 우리가 미리 등록 해놓은 이름들
2. 사용자가 사용했던 이름들

위 2개 묶어서 완성되게 하면 좋겠네요

**Comment by chanoo** [comment]
말씀 하신대로 timer type 정도는 넣는게 좋겠네요!

exam, pomodoro, focus

**Comment by chanoo** [comment]
지금 타이머 기능 개발 중이라 이 이슈부터 개발 부탁드려요~

**Comment by foxsea** [comment]
StudySession에 timerName, timerType 추가
