### ISSUE TITLE
친구 목록에서 공부 시간 체크 오료 수정

### ISSUE THREAD

**Issue by chanoo** [chanoo/klock-api#75]
월요일 ~ 일요일까지 누적된 공부 시간을 표시되도록 수정

<img width="438" alt="스크린샷 2024-03-04 오전 11 33 23" src="https://github.com/chanoo/klock-api/assets/3335290/ee2d1d68-2903-4f6a-ab2e-ac729dfbf7ab">

**Comment by chanoo** [comment]
친구 목록에 나(ME)도 나오도록 해주세요.

**Comment by foxsea** [comment]
@chanoo 월요일 ~ 일요일까지 누적된 공부 시간을 표시되도록 수정
-> 전체 누적이 아니라 조회일 기준 해당 주(week)의 누적 공부 일자를 말하는건가? 좀 더 설명해줘.

**Comment by chanoo** [comment]
3월 4일(월)부터 시작해서 10일까지 누적이 됩니다
그러고 3월 11일이 되면 다시 누적되기 시작 합니다.
매주 월요일부터 누적이 되기 시작한다고 생각하면 됩니다~!

@foxsea

**Comment by foxsea** [comment]
> 3월 4일(월)부터 시작해서 10일까지 누적이 됩니다 그러고 3월 11일이 되면 리셋되고 다시 누적되기 시작 합니다. 매주 월요일부터 누적이 되기 시작한다고 생각하면 됩니다~!
> 
> @foxsea

그러면 이거 따로 테이블 만들어서 기록해야겠네.

**Comment by chanoo** [comment]
회워 테이블과 상관 없는 정보이긴 한데
회원 테이블에 누적 정보 컬럼을 추가해서
공부 끝날때마다 월요일부터 일요일 자정까지 공부한거 계산해서 업데이트 치는것도 하나의 방법일 듯 합니다
